[tox]
envlist = py39, py310, py311
isolated_build = True

[testenv]
deps =
pytest
pytest-cov
setenv =
CI = true
commands =
pytest {posargs:tests} --cov=nfc_library

[testenv:lint]
deps =
black
isort
flake8
commands =
black --check nfc_library tests
isort --check nfc_library tests
flake8 nfc_library tests
